"""EREN AI Recommendation Context.

This package contains the AI Recommendation bounded context,
which handles recommendations generated by the AI system.

Architecture:
- domain/entities: AIRecommendation aggregate
- domain/value_objects: RecommendationStatus, Confidence, etc.
- domain/services: RecommendationService
- domain/repositories: Repository interfaces
"""

from .domain import (
    AcceptanceNote,
    AIRecommendation,
    RecommendationCategory,
    RecommendationConfidence,
    RecommendationRepository,
    RecommendationService,
    RecommendationStatus,
    RecommendationUrgency,
    RejectionReason,
)

__all__ = [
    # Entities
    "AIRecommendation",
    # Value Objects
    "RecommendationStatus",
    "RecommendationCategory",
    "RecommendationConfidence",
    "RejectionReason",
    "AcceptanceNote",
    "RecommendationUrgency",
    # Services
    "RecommendationService",
    # Repositories
    "RecommendationRepository",
]
