"""Type definitions for the Cognitive Context System.

Provides comprehensive type definitions for context, blackboard entries,
and related structures.

Architecture only — no business logic, no AI.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum, IntEnum
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    pass


# =============================================================================
# Context Status
# =============================================================================


class ContextStatus(IntEnum):
    """Status of the cognitive context."""

    INITIALIZING = 0  # Context being created
    PROCESSING = 1  # Active processing
    PENDING_EVIDENCE = 2  # Waiting for more evidence
    PENDING_HYPOTHESIS = 3  # Waiting for hypotheses
    PENDING_DIAGNOSIS = 4  # Waiting for diagnosis
    COMPLETED = 5  # Processing complete
    FAILED = 6  # Processing failed
    CANCELLED = 7  # Processing cancelled
    EXPIRED = 8  # Context expired


class ProcessingStage(IntEnum):
    """Stage of cognitive processing."""

    INTENTION = 10  # Understanding user intention
    CONTEXT_BUILDING = 20  # Building context
    KNOWLEDGE_RETRIEVAL = 30  # Retrieving knowledge
    MEMORY_RETRIEVAL = 40  # Retrieving memories
    HYPOTHESIS_GENERATION = 50  # Generating hypotheses
    EVIDENCE_COLLECTION = 60  # Collecting evidence
    DIAGNOSIS = 70  # Making diagnosis
    WORKFLOW_SELECTION = 80  # Selecting workflow
    EXECUTION = 90  # Executing plan
    RESPONSE = 100  # Generating response


# =============================================================================
# Confidence Level
# =============================================================================


class ConfidenceLevel(IntEnum):
    """Confidence level for conclusions."""

    NONE = 0  # No confidence
    VERY_LOW = 10  # Speculative
    LOW = 25  # Low confidence
    MODERATE = 50  # Moderate confidence
    HIGH = 75  # High confidence
    VERY_HIGH = 90  # Very high confidence
    CERTAIN = 100  # Certain


@dataclass
class Confidence:
    """Confidence score with metadata."""

    level: ConfidenceLevel = ConfidenceLevel.NONE
    score: float = 0.0  # 0.0 to 1.0
    reasons: tuple[str, ...] = field(default_factory=tuple)
    supporting_evidence: tuple[str, ...] = field(default_factory=tuple)
    contradicting_evidence: tuple[str, ...] = field(default_factory=tuple)

    def is_confident(self, threshold: float = 0.5) -> bool:
        """Check if confidence exceeds threshold."""
        return self.score >= threshold

    def is_certain(self) -> bool:
        """Check if certainty level is high."""
        return self.level >= ConfidenceLevel.HIGH


# =============================================================================
# Evidence and Hypothesis
# =============================================================================


class EvidenceType(str, Enum):
    """Type of evidence."""

    OBSERVATION = "observation"  # Direct observation
    MEASUREMENT = "measurement"  # Quantitative measurement
    HISTORICAL = "historical"  # Historical data
    DOCUMENTED = "documented"  # From documentation
    REPORTED = "reported"  # User reported
    DERIVED = "derived"  # Derived from other evidence
    TEMPORARY = "temporary"  # Temporary hypothesis


class EvidenceSource(str, Enum):
    """Source of evidence."""

    USER = "user"  # User provided
    DEVICE = "device"  # Device data
    SENSOR = "sensor"  # Sensor reading
    KNOWLEDGE_BASE = "knowledge_base"  # From KB
    MEMORY = "memory"  # From memory
    ENGINE = "engine"  # Generated by engine
    MANUAL = "manual"  # From technical manual
    STANDARD = "standard"  # From standards


@dataclass
class Evidence:
    """A piece of evidence in the context."""

    evidence_id: str
    evidence_type: EvidenceType
    source: EvidenceSource
    content: str | dict
    confidence: Confidence = field(default_factory=Confidence)
    timestamp: str = ""
    engine_id: str = ""  # Engine that generated this evidence
    tags: tuple[str, ...] = field(default_factory=tuple)
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Set timestamp if not provided."""
        if not self.timestamp:
            self.timestamp = datetime.now(timezone.utc).isoformat()


@dataclass
class Hypothesis:
    """A hypothesis in the context."""

    hypothesis_id: str
    description: str
    probability: float = 0.5  # 0.0 to 1.0
    confidence: Confidence = field(default_factory=Confidence)
    supporting_evidence: tuple[str, ...] = field(default_factory=tuple)  # Evidence IDs
    contradicting_evidence: tuple[str, ...] = field(default_factory=tuple)
    status: str = "active"  # active, confirmed, rejected, pending
    rank: int = 0  # Priority rank (lower is higher priority)
    created_at: str = ""
    engine_id: str = ""
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Set timestamp if not provided."""
        if not self.created_at:
            self.created_at = datetime.now(timezone.utc).isoformat()


# =============================================================================
# Observation
# =============================================================================


@dataclass
class Observation:
    """An observation made by a motor."""

    observation_id: str
    content: str | dict
    observation_type: str  # e.g., "device_error", "user_input", "system_state"
    confidence: Confidence = field(default_factory=Confidence)
    timestamp: str = ""
    engine_id: str = ""
    is_final: bool = False  # Whether this is a final observation

    def __post_init__(self) -> None:
        """Set timestamp if not provided."""
        if not self.timestamp:
            self.timestamp = datetime.now(timezone.utc).isoformat()


# =============================================================================
# Context Metadata
# =============================================================================


@dataclass
class UserContext:
    """User information in the context."""

    user_id: str = ""
    user_name: str = ""
    role: str = ""  # biomedical_engineer, nurse, doctor, admin
    permissions: tuple[str, ...] = field(default_factory=tuple)


@dataclass
class HospitalContext:
    """Hospital information in the context."""

    hospital_id: str = ""
    hospital_name: str = ""
    department: str = ""
    location: str = ""


@dataclass
class DeviceContext:
    """Device information in the context."""

    device_id: str = ""
    device_name: str = ""
    device_type: str = ""
    manufacturer: str = ""
    model: str = ""
    serial_number: str = ""
    location: str = ""
    risk_class: str = ""  # Class I, II, III


@dataclass
class IncidentContext:
    """Incident information in the context."""

    incident_id: str = ""
    incident_type: str = ""
    priority: str = ""  # low, medium, high, critical
    status: str = ""


# =============================================================================
# Processing Results
# =============================================================================


@dataclass
class IntentResult:
    """Result of intention understanding."""

    intent: str = ""
    entities: dict = field(default_factory=dict)
    confidence: Confidence = field(default_factory=Confidence)


@dataclass
class PlanResult:
    """Result of planning."""

    plan_id: str = ""
    steps: tuple[dict, ...] = field(default_factory=tuple)
    estimated_duration: float = 0.0


@dataclass
class DiagnosisResult:
    """Result of diagnosis."""

    diagnosis: str = ""
    diagnosis_code: str = ""
    confidence: Confidence = field(default_factory=Confidence)
    differential_diagnoses: tuple[str, ...] = field(default_factory=tuple)


@dataclass
class WorkflowResult:
    """Result of workflow execution."""

    workflow_id: str = ""
    workflow_name: str = ""
    actions_taken: tuple[dict, ...] = field(default_factory=tuple)
    outcome: str = ""


@dataclass
class ToolUsage:
    """Record of a tool being used."""

    tool_id: str
    tool_name: str
    parameters: dict = field(default_factory=dict)
    result: Any = None
    duration_ms: float = 0.0
    success: bool = True


@dataclass
class ResponseResult:
    """Final response result."""

    content: str = ""
    format: str = "text"  # text, json, markdown
    references: tuple[str, ...] = field(default_factory=tuple)
    confidence: Confidence = field(default_factory=Confidence)


# =============================================================================
# Blackboard Entry
# =============================================================================


class BlackboardEntryType(str, Enum):
    """Types of blackboard entries."""

    EVIDENCE = "evidence"
    HYPOTHESIS = "hypothesis"
    OBSERVATION = "observation"
    PLAN = "plan"
    DIAGNOSIS = "diagnosis"
    WORKFLOW = "workflow"
    TOOL = "tool"
    RESPONSE = "response"
    METADATA = "metadata"


@dataclass
class BlackboardEntry:
    """An entry on the cognitive blackboard.

    All motors write to this shared space. Entries are immutable once created
    and can only be superseded by new entries.
    """

    entry_id: str
    entry_type: BlackboardEntryType
    content: Any
    author_engine: str  # Engine that created this entry
    timestamp: str = ""
    version: int = 1
    parent_entry_id: str = ""  # For versioning
    superseded_by: str = ""  # If this entry was superseded
    confidence: Confidence = field(default_factory=Confidence)
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Set timestamp if not provided."""
        if not self.timestamp:
            self.timestamp = datetime.now(timezone.utc).isoformat()

    def is_active(self) -> bool:
        """Check if entry is active (not superseded)."""
        return not self.superseded_by


# =============================================================================
# Context Metadata
# =============================================================================


@dataclass
class ProcessingMetadata:
    """Metadata about the processing itself."""

    correlation_id: str = ""
    session_id: str = ""
    started_at: str = ""
    updated_at: str = ""
    completed_at: str = ""
    duration_ms: float = 0.0
    stage: ProcessingStage = ProcessingStage.INTENTION
    active_engines: tuple[str, ...] = field(default_factory=tuple)
    completed_engines: tuple[str, ...] = field(default_factory=tuple)
    errors: tuple[dict, ...] = field(default_factory=tuple)


@dataclass
class ContextMetadata:
    """Additional context metadata."""

    created_at: str = ""
    updated_at: str = ""
    version: int = 1
    tags: tuple[str, ...] = field(default_factory=tuple)
    source: str = ""  # api, voice, event, scheduled

    def __post_init__(self) -> None:
        """Set timestamps if not provided."""
        timestamp = datetime.now(timezone.utc).isoformat()
        if not self.created_at:
            self.created_at = timestamp
        if not self.updated_at:
            self.updated_at = timestamp


# =============================================================================
# Filter and Query Types
# =============================================================================


@dataclass
class ContextFilter:
    """Filter for context queries."""

    status: ContextStatus | None = None
    user_id: str | None = None
    hospital_id: str | None = None
    device_id: str | None = None
    session_id: str | None = None
    created_after: str | None = None
    created_before: str | None = None
    has_hypothesis: bool | None = None
    min_confidence: float | None = None


@dataclass
class BlackboardFilter:
    """Filter for blackboard queries."""

    entry_type: BlackboardEntryType | None = None
    author_engine: str | None = None
    is_active: bool = True
    created_after: str | None = None
    created_before: str | None = None
