"""Type definitions for the Cognitive Reasoning Engine.

Provides comprehensive type definitions for reasoning operations.

Architecture only — no AI, no business logic.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum, IntEnum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


# =============================================================================
# Hypothesis Types
# =============================================================================


class HypothesisStatus(IntEnum):
    """Status of a hypothesis."""

    ACTIVE = 0  # Active, under evaluation
    SUPPORTED = 1  # Has supporting evidence
    CONTRADICTED = 2  # Has contradicting evidence
    CONFIRMED = 3  # Confirmed by evidence
    REJECTED = 4  # Rejected by evidence
    PENDING = 5  # Awaiting evidence
    ARCHIVED = 6  # Archived, not considered


class HypothesisPriority(IntEnum):
    """Priority of a hypothesis."""

    CRITICAL = 100
    HIGH = 75
    MEDIUM = 50
    LOW = 25


@dataclass(frozen=True, slots=True)
class Hypothesis:
    """A hypothesis in the reasoning process.

    A hypothesis is a potential explanation for an observation.
    Multiple hypotheses can coexist.
    """

    hypothesis_id: str
    description: str
    status: HypothesisStatus = HypothesisStatus.ACTIVE
    probability: float = 0.5  # 0.0 to 1.0
    priority: HypothesisPriority = HypothesisPriority.MEDIUM
    rank: int = 0  # Rank among hypotheses (1 = highest)
    supporting_evidence: tuple[str, ...] = field(default_factory=tuple)
    contradicting_evidence: tuple[str, ...] = field(default_factory=tuple)
    created_at: str = ""
    updated_at: str = ""
    confidence_score: float = 0.5
    confidence_reasons: tuple[str, ...] = field(default_factory=tuple)
    tags: tuple[str, ...] = field(default_factory=tuple)
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Set timestamps if not provided."""
        if not self.created_at:
            object.__setattr__(self, 'created_at', datetime.now(UTC).isoformat())
        if not self.updated_at:
            object.__setattr__(self, 'updated_at', datetime.now(UTC).isoformat())

    def is_active(self) -> bool:
        """Check if hypothesis is active."""
        return self.status in (HypothesisStatus.ACTIVE, HypothesisStatus.SUPPORTED, HypothesisStatus.PENDING)

    def is_confirmed(self) -> bool:
        """Check if hypothesis is confirmed."""
        return self.status == HypothesisStatus.CONFIRMED

    def is_rejected(self) -> bool:
        """Check if hypothesis is rejected."""
        return self.status == HypothesisStatus.REJECTED


# =============================================================================
# Evidence Types
# =============================================================================


class EvidenceType(str, Enum):
    """Type of evidence."""

    OBSERVATION = "observation"  # Direct observation
    MEASUREMENT = "measurement"  # Quantitative measurement
    HISTORICAL = "historical"  # Historical data
    DOCUMENTED = "documented"  # From documentation
    REPORTED = "reported"  # User reported
    DERIVED = "derived"  # Derived from other evidence
    TEMPORARY = "temporary"  # Temporary assumption


class EvidenceSource(str, Enum):
    """Source of evidence."""

    USER = "user"  # User provided
    DEVICE = "device"  # Device data
    SENSOR = "sensor"  # Sensor reading
    KNOWLEDGE_BASE = "knowledge_base"  # From KB
    MEMORY = "memory"  # From memory
    ENGINE = "engine"  # Generated by engine
    MANUAL = "manual"  # From technical manual
    STANDARD = "standard"  # From standards


class EvidenceRelation(str, Enum):
    """Relation between evidence and hypothesis."""

    SUPPORTS = "supports"
    CONTRADICTS = "contradicts"
    NEUTRAL = "neutral"


@dataclass(frozen=True, slots=True)
class Evidence:
    """A piece of evidence in the reasoning process."""

    evidence_id: str
    evidence_type: EvidenceType
    source: EvidenceSource
    content: str | dict
    confidence: float = 0.5  # 0.0 to 1.0
    timestamp: str = ""
    related_hypotheses: tuple[str, ...] = field(default_factory=tuple)  # Hypothesis IDs
    relation: EvidenceRelation = EvidenceRelation.NEUTRAL
    weight: float = 1.0  # Evidence weight
    is_verified: bool = False
    is_temporary: bool = False
    parent_evidence_id: str = ""  # For derived evidence
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Set timestamp if not provided."""
        if not self.timestamp:
            object.__setattr__(self, 'timestamp', datetime.now(UTC).isoformat())

    def supports(self) -> bool:
        """Check if evidence supports hypotheses."""
        return self.relation == EvidenceRelation.SUPPORTS

    def contradicts(self) -> bool:
        """Check if evidence contradicts hypotheses."""
        return self.relation == EvidenceRelation.CONTRADICTS


# =============================================================================
# Confidence Types
# =============================================================================


class ConfidenceLevel(IntEnum):
    """Level of confidence."""

    NONE = 0  # No confidence
    VERY_LOW = 1  # Speculative
    LOW = 2  # Low confidence
    MODERATE = 3  # Moderate confidence
    HIGH = 4  # High confidence
    VERY_HIGH = 5  # Very high confidence
    CERTAIN = 6  # Certain


@dataclass(frozen=True, slots=True)
class ConfidenceScore:
    """A confidence score with metadata."""

    value: float  # 0.0 to 1.0
    level: ConfidenceLevel = ConfidenceLevel.MODERATE
    reasons: tuple[str, ...] = field(default_factory=tuple)
    supporting_factors: tuple[str, ...] = field(default_factory=tuple)
    contradicting_factors: tuple[str, ...] = field(default_factory=tuple)
    algorithm: str = "default"  # Algorithm used for calculation
    calculated_at: str = ""

    def __post_init__(self) -> None:
        """Set timestamp if not provided."""
        if not self.calculated_at:
            object.__setattr__(self, 'calculated_at', datetime.now(UTC).isoformat())

    def is_confident(self, threshold: float = 0.5) -> bool:
        """Check if confidence exceeds threshold."""
        return self.value >= threshold

    def is_uncertain(self) -> bool:
        """Check if confidence is below threshold."""
        return self.value < 0.3

    @classmethod
    def from_level(cls, level: ConfidenceLevel) -> ConfidenceScore:
        """Create confidence from level."""
        value_map = {
            ConfidenceLevel.NONE: 0.0,
            ConfidenceLevel.VERY_LOW: 0.15,
            ConfidenceLevel.LOW: 0.3,
            ConfidenceLevel.MODERATE: 0.5,
            ConfidenceLevel.HIGH: 0.75,
            ConfidenceLevel.VERY_HIGH: 0.9,
            ConfidenceLevel.CERTAIN: 1.0,
        }
        return cls(value=value_map.get(level, 0.5), level=level)


# =============================================================================
# Decision Types
# =============================================================================


class DecisionType(str, Enum):
    """Type of decision."""

    DIAGNOSTIC = "diagnostic"  # Diagnostic decision
    THERAPEUTIC = "therapeutic"  # Treatment decision
    OPERATIONAL = "operational"  # Operational decision
    RECOMMENDATION = "recommendation"  # Recommendation


class DecisionStatus(str, Enum):
    """Status of a decision."""

    PENDING = "pending"
    PROPOSED = "proposed"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    IMPLEMENTED = "implemented"


@dataclass(frozen=True, slots=True)
class Decision:
    """A decision derived from reasoning."""

    decision_id: str
    decision_type: DecisionType
    description: str
    status: DecisionStatus = DecisionStatus.PENDING
    based_on_hypothesis: str = ""  # Hypothesis ID
    confidence: ConfidenceScore = field(default_factory=ConfidenceScore)
    justification: tuple[str, ...] = field(default_factory=tuple)  # Justification text
    alternatives: tuple[str, ...] = field(default_factory=tuple)  # Alternative decisions considered
    selected_reason: str = ""  # Why this decision was selected
    created_at: str = ""
    implemented_at: str = ""
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Set timestamp if not provided."""
        if not self.created_at:
            object.__setattr__(self, 'created_at', datetime.now(UTC).isoformat())


# =============================================================================
# Reasoning Chain Types
# =============================================================================


class InferenceType(str, Enum):
    """Type of inference."""

    DEDUCTIVE = "deductive"  # General to specific
    INDUCTIVE = "inductive"  # Specific to general
    ABDUCTIVE = "abductive"  # Best explanation
    RULE_BASED = "rule_based"  # Rule application
    CASE_BASED = "case_based"  # Similar cases
    CAUSAL = "causal"  # Cause-effect


@dataclass(frozen=True, slots=True)
class ReasoningStep:
    """A single step in the reasoning chain."""

    step_id: str
    inference_type: InferenceType
    description: str
    premises: tuple[str, ...] = field(default_factory=tuple)  # Step IDs that are premises
    conclusions: tuple[str, ...] = field(default_factory=tuple)  # Step IDs that are conclusions
    hypothesis_id: str = ""  # Related hypothesis
    evidence_id: str = ""  # Related evidence
    confidence: ConfidenceScore = field(default_factory=ConfidenceScore)
    is_valid: bool = True
    invalid_reason: str = ""


@dataclass(frozen=True, slots=True)
class ReasoningChain:
    """A chain of reasoning steps."""

    chain_id: str
    hypothesis_id: str
    steps: tuple[ReasoningStep, ...] = field(default_factory=tuple)
    start_evidence: tuple[str, ...] = field(default_factory=tuple)
    final_conclusion: str = ""
    overall_confidence: ConfidenceScore = field(default_factory=ConfidenceScore)
    created_at: str = ""

    def __post_init__(self) -> None:
        """Set timestamp if not provided."""
        if not self.created_at:
            object.__setattr__(self, 'created_at', datetime.now(UTC).isoformat())


# =============================================================================
# Reasoning Trace
# =============================================================================


@dataclass(frozen=True, slots=True)
class ReasoningEvent:
    """An event in the reasoning trace."""

    event_id: str
    event_type: str  # hypothesis_created, evidence_added, etc.
    timestamp: str = ""
    actor: str = ""  # What triggered this event
    details: dict = field(default_factory=dict)
    related_ids: tuple[str, ...] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        """Set timestamp if not provided."""
        if not self.timestamp:
            object.__setattr__(self, 'timestamp', datetime.now(UTC).isoformat())


@dataclass(frozen=True, slots=True)
class ReasoningTrace:
    """Complete trace of reasoning process."""

    trace_id: str
    session_id: str
    events: tuple[ReasoningEvent, ...] = field(default_factory=tuple)
    hypothesis_graph: dict = field(default_factory=dict)  # Graph structure
    evidence_graph: dict = field(default_factory=dict)  # Graph structure
    created_at: str = ""
    updated_at: str = ""
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Set timestamps if not provided."""
        if not self.created_at:
            object.__setattr__(self, 'created_at', datetime.now(UTC).isoformat())
        if not self.updated_at:
            object.__setattr__(self, 'updated_at', datetime.now(UTC).isoformat())


# =============================================================================
# Reasoning State
# =============================================================================


class ReasoningStage(str, Enum):
    """Stage of reasoning process."""

    INITIAL = "initial"
    EVIDENCE_COLLECTION = "evidence_collection"
    HYPOTHESIS_GENERATION = "hypothesis_generation"
    HYPOTHESIS_EVALUATION = "hypothesis_evaluation"
    DECISION_MAKING = "decision_making"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass
class ReasoningState:
    """Current state of reasoning."""

    session_id: str
    stage: ReasoningStage = ReasoningStage.INITIAL
    active_hypotheses: int = 0
    total_hypotheses: int = 0
    active_evidence: int = 0
    total_evidence: int = 0
    best_hypothesis_id: str = ""
    best_hypothesis_confidence: float = 0.0
    decisions_count: int = 0
    reasoning_steps: int = 0
    started_at: str = ""
    updated_at: str = ""
    metadata: dict = field(default_factory=dict)


# =============================================================================
# Reasoning Metrics
# =============================================================================


@dataclass
class ReasoningMetrics:
    """Metrics for reasoning process."""

    session_id: str
    hypotheses_generated: int = 0
    hypotheses_confirmed: int = 0
    hypotheses_rejected: int = 0
    evidence_collected: int = 0
    evidence_analyzed: int = 0
    reasoning_steps: int = 0
    decisions_generated: int = 0
    average_confidence: float = 0.0
    total_reasoning_time_ms: float = 0.0
    chains_created: int = 0
    inferences_deductive: int = 0
    inferences_inductive: int = 0
    inferences_abductive: int = 0


# =============================================================================
# Strategy Types
# =============================================================================


class ReasoningStrategy(str, Enum):
    """Strategy for reasoning."""

    EXHAUSTIVE = "exhaustive"  # Consider all hypotheses
    FOCUSED = "focused"  # Focus on most likely
    EVIDENCE_FIRST = "evidence_first"  # Collect evidence first
    HYPOTHESIS_FIRST = "hypothesis_first"  # Generate hypotheses first
    CONSTRAINT = "constraint"  # Use constraints


@dataclass
class StrategyConfig:
    """Configuration for reasoning strategy."""

    strategy: ReasoningStrategy = ReasoningStrategy.EXHAUSTIVE
    max_hypotheses: int = 10  # Maximum hypotheses to maintain
    confidence_threshold: float = 0.5  # Threshold for confirmation
    rejection_threshold: float = 0.1  # Threshold for rejection
    evidence_required: int = 1  # Min evidence for confirmation
