"""AIRecommendation aggregate root."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING

from core.shared import (
    AggregateRoot,
    ConcurrencyError,
    DeviceId,
    EngineerId,
    IncidentId,
    RecommendationId,
    TenantId,
)
from core.shared.events import (
    RecommendationAcceptedV2,
    RecommendationCreated,
    RecommendationRejectedV2,
    RecommendationFeedbackReceived,
)

from ..value_objects import (
    AcceptanceNote,
    RecommendationCategory,
    RecommendationConfidence,
    RecommendationStatus,
    RecommendationUrgency,
    RejectionReason,
)

if TYPE_CHECKING:
    pass


@dataclass(eq=False)
class AIRecommendation(AggregateRoot):
    """AI Recommendation aggregate root.

    AIRecommendation represents a recommendation generated by the AI system
    for a specific incident or device.

    Lifecycle:
    GENERATED → PENDING_REVIEW → ACCEPTED/REJECTED/PARTIALLY_ACCEPTED
                              ↘ EXPIRED/SUPERSEDED

    Invariants:
    1. Recommendation must have a valid confidence score
    2. Cannot accept/reject expired recommendations
    3. Only pending recommendations can be accepted/rejected
    """

    # Identity
    tenant_id: TenantId
    incident_id: IncidentId | None
    device_id: DeviceId

    # Content
    title: str
    description: str
    rationale: str
    category: RecommendationCategory

    # AI metadata
    confidence: RecommendationConfidence
    model_version: str

    # Priority and urgency
    urgency: RecommendationUrgency = field(default_factory=RecommendationUrgency.scheduled)

    # State
    status: RecommendationStatus = field(default_factory=RecommendationStatus.generated)

    # Feedback
    rejection_reason: RejectionReason | None = None
    acceptance_note: AcceptanceNote | None = None
    engineer_feedback: str | None = None

    # Timing
    expires_at: datetime = field(default_factory=lambda: datetime.now(UTC) + timedelta(days=7))
    reviewed_at: datetime | None = None
    reviewed_by: EngineerId | None = None

    # Supersession
    superseded_by: RecommendationId | None = None
    supersedes: list[RecommendationId] = field(default_factory=list)

    def __post_init__(self) -> None:
        super().__post_init__()
        self._validate()
        # Publish event
        self.add_event(
            RecommendationCreated(
                recommendation_id=str(self.id),
                incident_id=str(self.incident_id) if self.incident_id else "",
                device_id=str(self.device_id),
                title=self.title,
                confidence=self.confidence.score,
                category=str(self.category),
                model_version=self.model_version,
            ),
        )

    def _validate(self) -> None:
        """Validate invariant constraints."""
        if not self.title or not self.title.strip():
            msg = "Recommendation title cannot be empty"
            raise ValueError(msg)
        if not self.description or not self.description.strip():
            msg = "Recommendation description cannot be empty"
            raise ValueError(msg)

    def accept(
        self,
        engineer_id: EngineerId,
        note: AcceptanceNote | None = None,
        modifications: str | None = None,
        expected_version: int = 1,
    ) -> None:
        """Accept the recommendation."""
        self._assert_version(expected_version)

        if not self.status.can_be_modified():
            msg = f"Cannot accept recommendation in status {self.status}"
            raise ValueError(msg)

        if self._is_expired():
            msg = "Cannot accept expired recommendation"
            raise ValueError(msg)

        self._unlock_for_mutation()
        self.status = RecommendationStatus.accepted()
        self.reviewed_at = datetime.now(UTC)
        self.reviewed_by = engineer_id
        self.acceptance_note = note
        self._relock_after_mutation()

        self.add_event(
            RecommendationAcceptedV2(
                recommendation_id=str(self.id),
                engineer_id=str(engineer_id),
                modifications=modifications or "",
                note=note.content if note else "",
            ),
        )

    def reject(
        self,
        engineer_id: EngineerId,
        reason: RejectionReason,
        feedback: str | None = None,
        expected_version: int = 1,
    ) -> None:
        """Reject the recommendation."""
        self._assert_version(expected_version)

        if not self.status.can_be_modified():
            msg = f"Cannot reject recommendation in status {self.status}"
            raise ValueError(msg)

        if self._is_expired():
            msg = "Cannot reject expired recommendation"
            raise ValueError(msg)

        self._unlock_for_mutation()
        self.status = RecommendationStatus.rejected()
        self.rejection_reason = reason
        self.engineer_feedback = feedback
        self.reviewed_at = datetime.now(UTC)
        self.reviewed_by = engineer_id
        self._relock_after_mutation()

        self.add_event(
            RecommendationRejectedV2(
                recommendation_id=str(self.id),
                engineer_id=str(engineer_id),
                reason_code=reason.reason_code,
                reason_description=reason.description,
                feedback=feedback or "",
            ),
        )

    def partially_accept(
        self,
        engineer_id: EngineerId,
        note: AcceptanceNote,
        accepted_parts: str,
        rejected_parts: str,
        expected_version: int = 1,
    ) -> None:
        """Partially accept the recommendation."""
        self._assert_version(expected_version)

        if not self.status.can_be_modified():
            msg = f"Cannot partially accept recommendation in status {self.status}"
            raise ValueError(msg)

        self._unlock_for_mutation()
        self.status = RecommendationStatus.partially_accepted()
        self.acceptance_note = note
        self.engineer_feedback = f"Accepted: {accepted_parts}\nRejected: {rejected_parts}"
        self.reviewed_at = datetime.now(UTC)
        self.reviewed_by = engineer_id
        self._relock_after_mutation()

    def provide_feedback(
        self,
        engineer_id: EngineerId,
        feedback: str,
        expected_version: int = 1,
    ) -> None:
        """Provide feedback on the recommendation."""
        self._assert_version(expected_version)

        self._unlock_for_mutation()
        self.engineer_feedback = feedback
        self._relock_after_mutation()

        self.add_event(
            RecommendationFeedbackReceived(
                recommendation_id=str(self.id),
                engineer_id=str(engineer_id),
                feedback=feedback,
                current_status=str(self.status),
            ),
        )

    def expire(self) -> None:
        """Mark the recommendation as expired."""
        if self.status.is_terminal():
            msg = f"Cannot expire recommendation in terminal status {self.status}"
            raise ValueError(msg)

        self._unlock_for_mutation()
        self.status = RecommendationStatus.expired()
        self._relock_after_mutation()

    def supersede(self, new_recommendation_id: RecommendationId) -> None:
        """Mark this recommendation as superseded by a new one."""
        if self.status.is_terminal():
            msg = f"Cannot supersede recommendation in terminal status {self.status}"
            raise ValueError(msg)

        self._unlock_for_mutation()
        self.status = RecommendationStatus.superseded()
        self.superseded_by = new_recommendation_id
        self._relock_after_mutation()

    def add_superseded(self, old_recommendation_id: RecommendationId) -> None:
        """Track a recommendation that this one supersedes."""
        if old_recommendation_id not in self.supersedes:
            self._unlock_for_mutation()
            self.supersedes.append(old_recommendation_id)
            self._relock_after_mutation()

    def _is_expired(self) -> bool:
        """Check if recommendation is expired."""
        return datetime.now(UTC) > self.expires_at

    def is_high_confidence(self) -> bool:
        """Check if this is a high confidence recommendation."""
        return self.confidence.is_high()

    def is_low_confidence(self) -> bool:
        """Check if this is a low confidence recommendation."""
        return self.confidence.is_low()

    def is_urgent(self) -> bool:
        """Check if this is an urgent recommendation."""
        return self.urgency.value == "immediate"

    def to_dict(self) -> dict:
        """Convert to dictionary for persistence."""
        base = super().to_dict()
        base.update(
            {
                "tenant_id": str(self.tenant_id),
                "incident_id": str(self.incident_id) if self.incident_id else None,
                "device_id": str(self.device_id),
                "title": self.title,
                "description": self.description,
                "rationale": self.rationale,
                "category": str(self.category),
                "confidence_score": self.confidence.score,
                "confidence_evidence_count": self.confidence.evidence_count,
                "model_version": self.model_version,
                "urgency": str(self.urgency),
                "status": str(self.status),
                "rejection_reason_code": self.rejection_reason.reason_code if self.rejection_reason else None,
                "rejection_reason_description": self.rejection_reason.description if self.rejection_reason else None,
                "acceptance_note": self.acceptance_note.content if self.acceptance_note else None,
                "engineer_feedback": self.engineer_feedback,
                "expires_at": self.expires_at.isoformat(),
                "reviewed_at": self.reviewed_at.isoformat() if self.reviewed_at else None,
                "reviewed_by": str(self.reviewed_by) if self.reviewed_by else None,
                "superseded_by": str(self.superseded_by) if self.superseded_by else None,
                "supersedes": [str(r) for r in self.supersedes],
            },
        )
        return base
